In [1]:
!pip install PyDrive

In [0]:
import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import zipfile
zip_ref = zipfile.ZipFile("/content/drive/My Drive/train.zip", 'r')
zip_ref.extractall("/tmp")
zip_ref.close()

In [10]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm

Using TensorFlow backend.


In [0]:
train = pd.read_csv('/tmp/train/train.csv')

In [12]:
train_image = []
for i in tqdm(range(train.shape[0])):
    img = image.load_img('/tmp/train/train/'+train['id'][i].astype('str')+'.png', target_size=(28,28,1), grayscale=True)
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
X = np.array(train_image)

  0%|          | 0/60000 [00:00<?, ?it/s]/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py:104: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
100%|██████████| 60000/60000 [00:18<00:00, 3278.07it/s]


In [16]:
y=train['label'].values
print(y)
y = to_categorical(y)
print(y)

[9 0 0 ... 3 0 5]
[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
y

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [18]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [19]:
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [20]:
model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 48000 samples, validate on 12000 samples
Epoch 1/20





48000/48000 [==============================] - 24s 510us/step - loss: 0.5166 - acc: 0.8168 - val_loss: 0.3226 - val_acc: 0.8808
Epoch 2/20
48000/48000 [==============================] - 9s 188us/step - loss: 0.3445 - acc: 0.8755 - val_loss: 0.2701 - val_acc: 0.9020
Epoch 3/20
48000/48000 [==============================] - 9s 189us/step - loss: 0.2964 - acc: 0.8917 - val_loss: 0.2479 - val_acc: 0.9062
Epoch 4/20
48000/48000 [==============================] - 9s 187us/step - loss: 0.2616 - acc: 0.9043 - val_loss: 0.2473 - val_acc: 0.9070
Epoch 5/20
48000/48000 [==============================] - 9s 186us/step - loss: 0.2389 - acc: 0.9115 - val_loss: 0.2369 - val_acc: 0.9147
Epoch 6/20
48000/48000 [==============================] - 9s 189us/step - loss: 0.2163 - acc: 0.9201 - val_loss: 0.2318 - val_acc: 0.9155
Epoch 7/20
48000/48

In [0]:
model.save('vision_challange.hdf5')

In [0]:
model.save_weights('vision_weights.hdf5')

In [0]:
zipp_ref = zipfile.ZipFile("/content/drive/My Drive/test.zip", 'r')
zipp_ref.extractall("/tmp")
zipp_ref.close()

In [0]:
test = pd.read_csv('/tmp/test/test.csv')

In [27]:
test_image = []
for i in tqdm(range(test.shape[0])):
    img = image.load_img('/tmp/test/test/'+test['id'][i].astype('str')+'.png', target_size=(28,28,1), grayscale=True)
    img = image.img_to_array(img)
    img = img/255
    test_image.append(img)
test = np.array(test_image)

  0%|          | 0/10000 [00:00<?, ?it/s]/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py:104: UserWarning: grayscale is deprecated. Please use color_mode = "grayscale"
  warnings.warn('grayscale is deprecated. Please use '
100%|██████████| 10000/10000 [00:03<00:00, 3252.80it/s]


In [0]:
prediction = model.predict_classes(test)

In [0]:
sample = pd.read_csv('/content/drive/My Drive/submission.csv')
sample['label'] = prediction
sample.to_csv('sample_cnn.csv', header=True, index=False)

adc.json  drive/  sample_data/  vision_challange.hdf5  vision_weights.hdf5
